///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class getAttendanceOverallattperformanceOverall {
/*
{
  "subjectname": "DLVS",
  "percentage": 63.83,
  "practical": "--",
  "colorcode1": "#dd8732",
  "colorcode2": null
}
*/

  String subjectname;
  String percentage;
  String practical;
  String colorcode1;
  String colorcode2;

  getAttendanceOverallattperformanceOverall({
    this.subjectname,
    this.percentage,
    this.practical,
    this.colorcode1,
    this.colorcode2,
  });
  getAttendanceOverallattperformanceOverall.fromJson(
      Map<String, dynamic> json) {
    subjectname = json['subjectname']?.toString();
    percentage = json['percentage']?.toString();
    practical = json['practical']?.toString();
    colorcode1 = json['colorcode1']?.toString();
    colorcode2 = json['colorcode2']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subjectname'] = subjectname;
    data['percentage'] = percentage;
    data['practical'] = practical;
    data['colorcode1'] = colorcode1;
    data['colorcode2'] = colorcode2;
    return data;
  }
}

class getAttendanceOverallattperformance {
/*
{
  "overall": [
    {
      "subjectname": "DLVS",
      "percentage": 63.83,
      "practical": "--",
      "colorcode1": "#dd8732",
      "colorcode2": null
    }
  ],
  "totalpercentage": "61.63",
  "colorcode": "#dd8732"
}
*/

  List<getAttendanceOverallattperformanceOverall> overall;
  String totalpercentage;
  String colorcode;

  getAttendanceOverallattperformance({
    this.overall,
    this.totalpercentage,
    this.colorcode,
  });
  getAttendanceOverallattperformance.fromJson(Map<String, dynamic> json) {
    if (json['overall'] != null) {
      final v = json['overall'];
      final arr0 = <getAttendanceOverallattperformanceOverall>[];
      v.forEach((v) {
        arr0.add(getAttendanceOverallattperformanceOverall.fromJson(v));
      });
      overall = arr0;
    }
    totalpercentage = json['totalpercentage']?.toString();
    colorcode = json['colorcode']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (overall != null) {
      final v = overall;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['overall'] = arr0;
    }
    data['totalpercentage'] = totalpercentage;
    data['colorcode'] = colorcode;
    return data;
  }
}

class getAttendanceAttandanceTwoweeksessions {
/*
{
  "present": 36,
  "absent": 28,
  "nosessions": 20
}
*/

  String present;
  String absent;
  String nosessions;

  getAttendanceAttandanceTwoweeksessions({
    this.present,
    this.absent,
    this.nosessions,
  });
  getAttendanceAttandanceTwoweeksessions.fromJson(Map<String, dynamic> json) {
    present = json['present']?.toString();
    absent = json['absent']?.toString();
    nosessions = json['nosessions']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['present'] = present;
    data['absent'] = absent;
    data['nosessions'] = nosessions;
    return data;
  }
}

class getAttendanceAttandanceDayobjectsSessions {
/*
{
  "session1": 2,
  "session2": 2,
  "session3": 2,
  "session4": 2,
  "session5": 2,
  "session6": 2,
  "session7": 2
}
*/

  String session1;
  String session2;
  String session3;
  String session4;
  String session5;
  String session6;
  String session7;

  getAttendanceAttandanceDayobjectsSessions({
    this.session1,
    this.session2,
    this.session3,
    this.session4,
    this.session5,
    this.session6,
    this.session7,
  });
  getAttendanceAttandanceDayobjectsSessions.fromJson(
      Map<String, dynamic> json) {
    session1 = json['session1']?.toString();
    session2 = json['session2']?.toString();
    session3 = json['session3']?.toString();
    session4 = json['session4']?.toString();
    session5 = json['session5']?.toString();
    session6 = json['session6']?.toString();
    session7 = json['session7']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['session1'] = session1;
    data['session2'] = session2;
    data['session3'] = session3;
    data['session4'] = session4;
    data['session5'] = session5;
    data['session6'] = session6;
    data['session7'] = session7;
    return data;
  }
}

class getAttendanceAttandanceDayobjects {
/*
{
  "day": "Today",
  "date": "Mon 24 Oct",
  "updatedon": "Mon 24 Oct  at 11:54 AM",
  "holiday": "false",
  "sessions": {
    "session1": 2,
    "session2": 2,
    "session3": 2,
    "session4": 2,
    "session5": 2,
    "session6": 2,
    "session7": 2
  }
}
*/

  String day;
  String date;
  String updatedon;
  String holiday;
  getAttendanceAttandanceDayobjectsSessions sessions;

  getAttendanceAttandanceDayobjects({
    this.day,
    this.date,
    this.updatedon,
    this.holiday,
    this.sessions,
  });
  getAttendanceAttandanceDayobjects.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toString();
    date = json['date']?.toString();
    updatedon = json['updatedon']?.toString();
    holiday = json['holiday']?.toString();
    sessions = (json['sessions'] != null)
        ? getAttendanceAttandanceDayobjectsSessions.fromJson(json['sessions'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
    data['date'] = date;
    data['updatedon'] = updatedon;
    data['holiday'] = holiday;
    if (sessions != null) {
      data['sessions'] = sessions.toJson();
    }
    return data;
  }
}

class getAttendanceAttandance {
/*
{
  "dayobjects": [
    {
      "day": "Today",
      "date": "Mon 24 Oct",
      "updatedon": "Mon 24 Oct  at 11:54 AM",
      "holiday": "false",
      "sessions": {
        "session1": 2,
        "session2": 2,
        "session3": 2,
        "session4": 2,
        "session5": 2,
        "session6": 2,
        "session7": 2
      }
    }
  ],
  "twoweeksessions": {
    "present": 36,
    "absent": 28,
    "nosessions": 20
  }
}
*/

  List<getAttendanceAttandanceDayobjects> dayobjects;
  getAttendanceAttandanceTwoweeksessions twoweeksessions;

  getAttendanceAttandance({
    this.dayobjects,
    this.twoweeksessions,
  });
  getAttendanceAttandance.fromJson(Map<String, dynamic> json) {
    if (json['dayobjects'] != null) {
      final v = json['dayobjects'];
      final arr0 = <getAttendanceAttandanceDayobjects>[];
      v.forEach((v) {
        arr0.add(getAttendanceAttandanceDayobjects.fromJson(v));
      });
      dayobjects = arr0;
    }
    twoweeksessions = (json['twoweeksessions'] != null)
        ? getAttendanceAttandanceTwoweeksessions
            .fromJson(json['twoweeksessions'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dayobjects != null) {
      final v = dayobjects;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['dayobjects'] = arr0;
    }
    if (twoweeksessions != null) {
      data['twoweeksessions'] = twoweeksessions.toJson();
    }
    return data;
  }
}

class getAttendance {
/*
{
  "attandance": {
    "dayobjects": [
      {
        "day": "Today",
        "date": "Mon 24 Oct",
        "updatedon": "Mon 24 Oct  at 11:54 AM",
        "holiday": "false",
        "sessions": {
          "session1": 2,
          "session2": 2,
          "session3": 2,
          "session4": 2,
          "session5": 2,
          "session6": 2,
          "session7": 2
        }
      }
    ],
    "twoweeksessions": {
      "present": 36,
      "absent": 28,
      "nosessions": 20
    }
  },
  "overallattperformance": {
    "overall": [
      {
        "subjectname": "DLVS",
        "percentage": 63.83,
        "practical": "--",
        "colorcode1": "#dd8732",
        "colorcode2": null
      }
    ],
    "totalpercentage": "61.63",
    "colorcode": "#dd8732"
  },
  "debug": ""
}
*/

  getAttendanceAttandance attandance;
  getAttendanceOverallattperformance overallattperformance;
  String debug;

  getAttendance({
    this.attandance,
    this.overallattperformance,
    this.debug,
  });
  getAttendance.fromJson(Map<String, dynamic> json) {
    attandance = (json['attandance'] != null)
        ? getAttendanceAttandance.fromJson(json['attandance'])
        : null;
    overallattperformance = (json['overallattperformance'] != null)
        ? getAttendanceOverallattperformance
            .fromJson(json['overallattperformance'])
        : null;
    debug = json['debug']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (attandance != null) {
      data['attandance'] = attandance.toJson();
    }
    if (overallattperformance != null) {
      data['overallattperformance'] = overallattperformance.toJson();
    }
    data['debug'] = debug;
    return data;
  }
}
